# Generated by Django 5.1.4 on 2024-12-25 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignerPaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_details', models.TextField()),
                ('designer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_info', to='accounts.user')),
            ],
        ),
    ]
