# Generated by Django 5.1.3 on 2025-02-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadAssset', '0004_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='assets/'),
        ),
    ]
