# Generated by Django 5.1.4 on 2025-01-14 06:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_game_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='words',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
