# Generated by Django 5.1.4 on 2025-01-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_game_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='file',
            field=models.FileField(blank=True, default='/game', null=True, upload_to='games/'),
        ),
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('html5', 'HTML5'), ('unity-webgl', 'Unity WebGL')], default='html5', max_length=50),
        ),
    ]
