# Generated by Django 5.1.4 on 2025-01-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_game_file_game_game_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='active',
        ),
        migrations.AlterField(
            model_name='game',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='games'),
        ),
    ]
