# Generated by Django 5.1.5 on 2025-01-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_remove_game_active_alter_game_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='games/name'),
        ),
    ]
