# Generated by Django 5.1.3 on 2025-01-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='thumnail',
            field=models.ImageField(default=True, upload_to='thumnail/%Y/%m'),
        ),
    ]
