# Generated by Django 5.1.3 on 2025-02-16 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_alter_asset_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset'),
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
