# Generated by Django 5.1.4 on 2025-01-14 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='request_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='requested_role',
            field=models.CharField(blank=True, choices=[('player', 'Player'), ('developer', 'Developer'), ('designer', 'Designer')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('player', 'Player'), ('developer', 'Developer'), ('designer', 'Designer')], default='player', max_length=20),
        ),
    ]
