# Generated by Django 5.1.5 on 2025-01-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_request_status_customuser_requested_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='request_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requested_role',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Player', 'Player'), ('Developer', 'Developer'), ('Designer', 'Designer')], default='Player', max_length=10),
        ),
    ]
