# Generated by Django 5.1.4 on 2025-01-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_request_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('player', 'Player'), ('developer', 'Developer'), ('designer', 'Designer'), ('admin', 'Admin')], default='player', max_length=10),
        ),
    ]
