# Generated by Django 5.1.5 on 2025-02-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_total_online_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('player', 'Player'), ('developer', 'Developer'), ('designer', 'Designer'), ('admin', 'Admin'), ('dev_des', 'Dev/Des')], default='player', max_length=10),
        ),
    ]
