# Generated by Django 5.1.5 on 2025-02-18 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CssClass', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FrameChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CssClass', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_use', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatar_class', to=settings.AUTH_USER_MODEL)),
                ('frame_avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rewards.frameavatar')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_use', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_class', to=settings.AUTH_USER_MODEL)),
                ('frame_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rewards.framechat')),
            ],
        ),
    ]
