# Generated by Django 5.1.4 on 2025-02-18 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameAva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=100)),
                ('CssClass', models.CharField(default='default-ava', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FrameChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=100)),
                ('CssClass', models.CharField(default='default-chat', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ava_frames', models.ManyToManyField(blank=True, to='rewards.frameava')),
                ('chat_frames', models.ManyToManyField(blank=True, to='rewards.framechat')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ava_frames', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rewards.frameava')),
                ('chat_frames', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rewards.framechat')),
            ],
        ),
    ]
