# Generated by Django 5.1.4 on 2025-02-16 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CssClass', models.CharField(default='default-chat', max_length=100)),
                ('code', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='tabelrewards',
            name='framechat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rewards.framechat'),
        ),
    ]
