# Generated by Django 5.1.5 on 2025-02-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frameavatar',
            name='price',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='framechat',
            name='price',
            field=models.IntegerField(default=100),
        ),
    ]
