# Generated by Django 5.1.4 on 2025-02-18 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='ava_frames',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='chat_frames',
        ),
        migrations.CreateModel(
            name='FrameAvaSohuu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CssClass', models.CharField(blank=True, max_length=100)),
                ('price', models.IntegerField(default=100)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rewards.inventory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FrameChatSohuu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CssClass', models.CharField(blank=True, max_length=100)),
                ('price', models.IntegerField(default=100)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rewards.inventory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
