# Generated by Django 5.1.5 on 2025-02-18 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_frameavatar_price_framechat_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='is_use',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='is_use',
        ),
        migrations.AddField(
            model_name='frameavatar',
            name='image',
            field=models.ImageField(default='default/gojo.jpg', upload_to='rewards/'),
        ),
        migrations.AddField(
            model_name='framechat',
            name='image',
            field=models.ImageField(default='default/gojo.jpg', upload_to='rewards/'),
        ),
        migrations.AlterField(
            model_name='frameavatar',
            name='CssClass',
            field=models.TextField(default='default-avatar', max_length=50),
        ),
        migrations.AlterField(
            model_name='framechat',
            name='CssClass',
            field=models.TextField(default='default-chat', max_length=50),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rewards.avatar')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rewards.chat')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
