# Generated by Django 5.1.4 on 2025-02-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0003_rename_tabelrewards_tablerewards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framechat',
            name='code',
            field=models.TextField(null=True),
        ),
    ]
