# Generated by Django 5.1.4 on 2025-02-18 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0004_alter_framechat_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='framechat',
            name='code',
        ),
    ]
