# Generated by Django 5.1.4 on 2025-02-18 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0005_remove_framechat_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameAva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CssClass', models.CharField(default='default-ava', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='tablerewards',
            name='frameava',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rewards.frameava'),
            preserve_default=False,
        ),
    ]
