# Generated by Django 5.1.4 on 2025-02-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0006_frameava_tablerewards_frameava'),
    ]

    operations = [
        migrations.AddField(
            model_name='frameava',
            name='is_buy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='frameava',
            name='price',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='framechat',
            name='is_buy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='framechat',
            name='price',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='frameava',
            name='CssClass',
            field=models.CharField(default='default-chat', max_length=100),
        ),
    ]
