# Generated by Django 5.1.4 on 2025-02-18 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0007_frameava_is_buy_frameava_price_framechat_is_buy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frameava',
            name='price',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='framechat',
            name='price',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='tablerewards',
            name='frameava',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rewards.frameava'),
        ),
        migrations.AlterField(
            model_name='tablerewards',
            name='framechat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rewards.framechat'),
        ),
    ]
