# Generated by Django 5.1.4 on 2025-02-18 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0008_alter_frameava_price_alter_framechat_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablerewards',
            name='frameava',
        ),
        migrations.RemoveField(
            model_name='tablerewards',
            name='framechat',
        ),
        migrations.AddField(
            model_name='frameava',
            name='frameava',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='rewards.tablerewards'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='framechat',
            name='framechat',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='rewards.tablerewards'),
            preserve_default=False,
        ),
    ]
