# Generated by Django 5.1.4 on 2025-02-18 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0009_remove_tablerewards_frameava_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='framechat',
            name='framechat',
        ),
        migrations.RemoveField(
            model_name='frameava',
            name='frameava',
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ava', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rewards.frameava')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rewards.framechat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='TableRewards',
        ),
    ]
