# Generated by Django 5.1.4 on 2025-02-18 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0012_shop_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='user',
        ),
    ]
