# Generated by Django 5.1.4 on 2025-02-18 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0014_alter_frameava_cssclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='ava',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rewards.frameava'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rewards.framechat'),
        ),
    ]
