# Generated by Django 5.1.4 on 2025-02-18 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0015_alter_inventory_ava_alter_inventory_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='ava',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rewards.frameava'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rewards.framechat'),
        ),
    ]
