# Generated by Django 5.1.4 on 2025-02-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0016_alter_inventory_ava_alter_inventory_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='frameava',
            name='is_buy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='framechat',
            name='is_buy',
            field=models.BooleanField(default=False),
        ),
    ]
