"""
Django settings for log project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bd10$d^_lu(h0=@x*m&h-5bfllu8k)86ndvma3huk@4z!ju(9p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# X_FRAME_OPTIONS = 'SAMEORIGIN'
ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'account',
    'game',
    'ckeditor',
    'ckeditor_uploader',
    'rest_framework', 
    # 'django_ckeditor_5',

]

# CKEDITOR_5_CUSTOM_CDN = "https://cdn.ckeditor.com/ckeditor5/39.0.1/classic/ckeditor.js"


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'log.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
           BASE_DIR / "templates",
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'log.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # Sử dụng MySQL
        'NAME': 'datagamehub',          # Tên cơ sở dữ liệu
        'USER': 'root',               # Tên người dùng MySQL
        'PASSWORD': 'sayonara',           # Mật khẩu MySQL
        'HOST': 'localhost',                   # Máy chủ (thường là localhost)
    }
}


AUTH_USER_MODEL = 'account.User'

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


CKEDITOR_UPLOAD_PATH = 'image/'



# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/'  # URL sau khi đăng nhập thành công
LOGOUT_REDIRECT_URL = '/'  # URL sau khi đăng xuất

# URL để truy cập các file static
STATIC_URL = '/static/'

# MEDIA_ROOT =  os.path.join(BASE_DIR, 'media')
MEDIA_ROOT = BASE_DIR / 'media'
# URL để truy cập các file media
MEDIA_URL = '/media/'

# Thư mục nơi lưu trữ file media
# MEDIA_ROOT = BASE_DIR / 'media'



# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'static'),
# ] 