# Generated by Django 5.1.4 on 2025-01-20 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=9999)),
                ('datecreate', models.DateField(auto_now_add=True)),
                ('reward', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('file', models.FileField(blank=True, null=True, upload_to='games/')),
                ('game_type', models.CharField(choices=[('html5', 'HTML5'), ('unity-webgl', 'Unity WebGL')], default='html5', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.CharField(max_length=9999)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('games', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
        ),
    ]
