# Generated by Django 5.1.4 on 2025-01-21 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_comment_words_alter_game_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_type',
        ),
    ]
