# Generated by Django 5.1.4 on 2025-01-21 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='user_id',
            new_name='user',
        ),
    ]
