# Generated by Django 5.1.5 on 2025-01-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_alter_game_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, default='empty.jpg', null=True, upload_to='image/'),
        ),
    ]
