# Generated by Django 5.1.3 on 2025-01-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_alter_game_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='leader_board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
