# Generated by Django 5.1.4 on 2025-02-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_lbhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='datecreate',
            field=models.DateField(auto_now_add=True, default='2025-2-2'),
            preserve_default=False,
        ),
    ]
