# Generated by Django 5.1.4 on 2025-02-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_comment_datecreate'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ApiLD',
            field=models.BooleanField(default=False),
        ),
    ]
