# Generated by Django 5.1.4 on 2025-02-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_game_apild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, default='empty.jpg', null=True, upload_to='games/image'),
        ),
    ]
