# Generated by Django 5.1.4 on 2025-02-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_alter_game_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, default='default/empty.jpg', null=True, upload_to='games/image'),
        ),
    ]
