# Generated by Django 5.1.5 on 2025-02-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_alter_game_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(default='default/gojo.jpg', upload_to='games/image'),
            preserve_default=False,
        ),
    ]
