# Generated by Django 5.1.5 on 2025-02-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0019_alter_game_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
