# Generated by Django 5.1.5 on 2025-02-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0022_alter_ratting_ratting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='ratting',
            field=models.FloatField(default=5),
        ),
    ]
