# Generated by Django 5.1.5 on 2025-02-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0025_alter_ratting_game_alter_ratting_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='datecreate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
